site_name: DBD - Documentation 
site_url: https://dbd.lachlan-dev.com/
theme:
  name: material
  custom_dir: overrides
  theme:
  palette:
    scheme: slate
nav:
    - Home: 'index.md'
    - 'Installation':
        - 'Locally': 'installation/basic.md'
        - 'Docker': 'installation/docker.md'
    - Creating Plugins: 'plugins.md'
plugins: []